version: '3.7'

services:
  pogoda:
    build: ./w_feed
    command:  >
      sh -c "python manage.py collectstatic --no-input &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - w_feed.env
    depends_on:
      - redis
      - worker
      - scheduler
  worker:
    image: pogoda_docker_pogoda
    command: python manage.py rqworker high default low
    env_file:
      - w_feed.env
    depends_on:
      - redis
  scheduler:
    image: pogoda_docker_pogoda
    command: python manage.py rqscheduler
    env_file:
      - w_feed.env
    depends_on:
      - redis
  redis:
    image: redis:5.0.7-alpine
    container_name: redis
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis_data:/data
volumes:
  redis_data: