version: '3.7'

services:
  pogoda:
    build: ./w_feed
    entrypoint: ["sh","/usr/src/app/entrypoint.sh"]
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - w_feed.env
    depends_on:
      - db
      - redis
  worker:
    image: pogoda_docker_pogoda
    command: python manage.py rqworker high default low
    env_file:
      - w_feed.env
    depends_on:
      - db
      - redis
  scheduler:
    image: pogoda_docker_pogoda
    command: python manage.py rqscheduler
    env_file:
      - w_feed.env
    depends_on:
      - db
      - redis
  redis:
    image: redis:5.0.7-alpine
    container_name: redis_pogoda
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis_data:/data
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgre sql/data/
    env_file:
      - db.env
    restart: always
volumes:
  redis_data:
  postgres_data:
