version: '3.7'

services:
  auth:
    build: ./w_feed
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./w_feed/:/usr/src/app/
    ports:
      - 8000:8000
    env_file: w_feed.env