version: '3.7'

services:
  pogoda:
    build: ./w_feed
#    entrypoint: ["sh","/usr/src/app/entrypoint.sh"]
    command:  python ./manage.py runserver 0.0.0.0:8000
#    volumes:
#      - ./w_feed/:/usr/src/app/
    ports:
      - 8000:8000
    env_file: w_feed.env
    environment:
      WAIT_HOSTS:
        -redis:6379
    depends_on:
      - redis
  worker:
    image: pogoda_docker_pogoda
    command: python manage.py rqworker high default low
    env_file: w_feed.env
    depends_on:
      - redis
  redis:
    image: redis:5.0.7-alpine
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis_data:/data
volumes:
  redis_data: