version: '3.7'

services:
  pogoda:
    build: ./w_feed
    entrypoint: ["sh","/usr/src/app/entrypoint.sh"]
    command: gunicorn -b 0.0.0.0:8000 -w 4 -k uvicorn.workers.UvicornWorker pogoda_feed.asgi:application
    ports:
      - 8000:8000
    env_file:
      - w_feed.env
    depends_on:
      - db
      - redis
    links:
      - api_date
  api_date:
    build: ./api_date
    command: gunicorn -w 1 -b 0.0.0.0:5000 wsgi:app
    expose:
      - 5000
  pogoda_ui:
    build: ./pogoda_ui
    entrypoint: ["sh","/usr/src/app/entrypoint.sh"]
    command: http-server ./dist -p=3000
    expose:
     - 3000
  worker:
    image: pogoda_docker_pogoda
    command: python manage.py rqworker high default low
    env_file:
      - w_feed.env
    depends_on:
      - db
      - redis
  scheduler:
    image: pogoda_docker_pogoda
    command: python manage.py rqscheduler
    env_file:
      - w_feed.env
    depends_on:
      - db
      - redis
  redis:
    image: redis:5.0.7-alpine
    container_name: redis_pogoda
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - redis_data:/data
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgre sql/data/
    env_file:
      - w_feed.env
    restart: on-failure
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 80:80
      - 8080:8080
    links:
      - pogoda
      - pogoda_ui
volumes:
  redis_data:
  postgres_data:
  static_volume:
  media_volume: