version: '3.7'

services:
  pogoda:
    build: ./w_feed
    entrypoint: ["sh","/usr/src/app/entrypoint.sh"]
    command: gunicorn pogoda_feed.wsgi:application --bind 0.0.0.0:8000
    expose: 
      - 8000
    env_file:
      - w_feed.env
    depends_on:
      - db
      - redis
  pogoda_ui:
    build: ./pogoda_ui
    entrypoint: ["sh","/usr/src/app/entrypoint.sh"]
    command: http-server ./dist -p=3000
    environment: 
      - API_HOST=http://pogoda:8000 
    expose: 
     - 3000
    links: 
      - pogoda
  worker:
    image: pogoda_docker_pogoda
    command: python manage.py rqworker high default low
    env_file:
      - w_feed.env
    depends_on:
      - db
      - redis
  scheduler:
    image: pogoda_docker_pogoda
    command: python manage.py rqscheduler
    env_file:
      - w_feed.env
    depends_on:
      - db
      - redis
  redis:
    image: redis:5.0.7-alpine
    container_name: redis_pogoda
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - redis_data:/data
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgre sql/data/
    env_file:
      - w_feed.env
    restart: always
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 80:80
      - 8080:8080
    depends_on:
      - pogoda
      - pogoda_ui
volumes:
  redis_data:
  postgres_data:
  static_volume:
  media_volume: